routes/web.php
<?php

Route::get('show','Controller@show');
Route::get('test','Controller@test');
Route::post('upload','Controller@upload')->name('upload');

Route::get("view_login","LoginController@view_login")->name('view_login');
Route::post("process_login","LoginController@process_login")->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get("welcome","Controller@welcome")->name('welcome');
	Route::get("logout","LoginController@logout")->name('logout');

	$controller = "CongTyController";
	Route::group(["prefix" => "cong_ty", 'as' => 'cong_ty.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::group(['middleware' => 'CheckSuperAdmin'],function() use ($controller){
			Route::get("view_insert","$controller@view_insert")->name("view_insert");
			Route::post("process_insert","$controller@process_insert")->name("process_insert");
			Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
			Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
			Route::get("delete/{ma}","$controller@delete")->name("delete");

			// xem nhân viên của công ty
			Route::get("view_nhan_vien_cua_cong_ty/{ma}","$controller@view_nhan_vien_cua_cong_ty")->name("view_nhan_vien_cua_cong_ty");
		});
	});

	$controller = "NhanVienController";
	Route::group(["prefix" => "nhan_vien", 'as' => 'nhan_vien.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");

		Route::get("view_import_excel","$controller@view_import_excel")->name("view_import_excel");
		Route::post("process_import_excel","$controller@process_import_excel")->name("process_import_excel");
	});

	Route::resource('cong_ty_demo','CongTyDemoController');
});

resources/views/menu.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<ul>
	<li>
		<a href="{{ route('cong_ty.view_all') }}">
			Quản lý công ty
		</a>
	</li>
	<li>
		<a href="{{ route('nhan_vien.view_all') }}">
			Quản lý nhân viên
		</a>
	</li>
</ul>
</body>
</html>

resources/views/show.blade.php
<img src="{{ asset('storage/image/QWgRlLGvcZHPkZgGaijTU8FpijFiX8rk0OKyAdYO.jpeg') }}">

resources/views/test.blade.php
<form action="{{ route('upload') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	Chọn ảnh
	<input type="file" name="file_anh" accept="image/*">
	<button>Đăng ảnh lên</button>
</form>

resources/views/view_login.blade.php
@if (Session::has('error'))
	{{ Session::get('error') }}
@endif
@if (Session::has('success'))
	{{ Session::get('success') }}
@endif

<form action="{{ route('process_login') }}" method="post">
	{{ csrf_field() }}
	Email
	<input type="email" name="email">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau">
	<br>
	<button>Đăng nhập</button>
</form>