routes/web.php
<?php

Route::get('show','Controller@show');
Route::get('test','Controller@test');
Route::post('upload','Controller@upload')->name('upload');

Route::get("view_login","LoginController@view_login")->name('view_login');
Route::post("process_login","LoginController@process_login")->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get("welcome","Controller@welcome")->name('welcome');
	Route::get("logout","LoginController@logout")->name('logout');

	$controller = "CongTyController";
	Route::group(["prefix" => "cong_ty", 'as' => 'cong_ty.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::group(['middleware' => 'CheckSuperAdmin'],function() use ($controller){
			Route::get("view_insert","$controller@view_insert")->name("view_insert");
			Route::post("process_insert","$controller@process_insert")->name("process_insert");
			Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
			Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
			Route::get("delete/{ma}","$controller@delete")->name("delete");

			// xem nhân viên của công ty
			Route::get("view_nhan_vien_cua_cong_ty/{ma}","$controller@view_nhan_vien_cua_cong_ty")->name("view_nhan_vien_cua_cong_ty");
		});
	});

	$controller = "NhanVienController";
	Route::group(["prefix" => "nhan_vien", 'as' => 'nhan_vien.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");

		Route::get("view_import_excel","$controller@view_import_excel")->name("view_import_excel");
		Route::post("process_import_excel","$controller@process_import_excel")->name("process_import_excel");
	});

	Route::resource('cong_ty_demo','CongTyDemoController');
});

app/Models/CongTy.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CongTy extends Model
{
    protected $table = 'cong_ty';
    protected $fillable = ['ten','sdt','email','dia_chi'];
    protected $primaryKey = 'ma';

    public $timestamps = false;
    public function array_nhan_vien()
    {
    	return $this->hasMany('App\Models\NhanVien', 'ma_cong_ty', 'ma');
    }
}

app/Http/Controllers/CongTyController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\Models\CongTy;

class CongTyController
{
    public function view_all(Request $rq)
    {
        $tim_kiem = $rq->tim_kiem;
        $title = 'Xem tất cả công ty';
        $array_cong_ty = CongTy::where('ten','like',"%$tim_kiem%")->paginate(3);

        return view('cong_ty.view_all',[
            'array_cong_ty' => $array_cong_ty,
            'title'         => $title,
            'tim_kiem'      => $tim_kiem,
        ]);
    }
    public function view_insert()
    {
    	return view('cong_ty.view_insert');
    }
    public function process_insert(Request $rq)
    {
    	CongTy::create($rq->all());

    	return redirect()->route('cong_ty.view_all')->with('sucess','Đã thêm thành công');
    }
    public function view_update($ma)
    {
    	$cong_ty = CongTy::find($ma);

    	return view('cong_ty.view_update',['cong_ty' => $cong_ty]);
    }
    public function process_update($ma,Request $rq)
    {
    	CongTy::find($ma)->update($rq->all());

    	return redirect()->route('cong_ty.view_all')->with('sucess','Đã sửa thành công');
    }
    public function delete($ma)
    {
    	CongTy::find($ma)->delete();

    	return redirect()->route('cong_ty.view_all')->with('sucess','Đã xoá thành công');
    }
    public function view_nhan_vien_cua_cong_ty($ma)
    {
        $array_nhan_vien = CongTy::with('array_nhan_vien')->find($ma);

        return $array_nhan_vien;
    }
}

resources/views/cong_ty/view_all.blade.php
@extends('layout.master')

@section('content')
<a href="{{ route('cong_ty.view_insert') }}">
	Thêm
</a>
@if (Session::has('sucess'))
	<h1>
		{{ Session::get('sucess') }}
	</h1>
@endif
<table class="table table-hover">
	<tr>
		<th>
			Tên
		</th>
		<th>
			SDT
		</th>
		<th>
			Email
		</th>
		<th>
			Địa chỉ
		</th>
		<th>
			Xem
		</th>
		@if (Session::get('cap_do')==1)
			<th>
				Sửa
			</th>
			<th>
				Xoá
			</th>
		@endif
	</tr>
	@foreach ($array_cong_ty as $cong_ty)
		<tr>
			<td>
				{{ $cong_ty->ten }}
			</td>
			<td>
				{{ $cong_ty->sdt }}
			</td>
			<td>
				{{ $cong_ty->email }}
			</td>
			<td>
				{{ $cong_ty->dia_chi }}
			</td>
			<td>
				<a href="{{ route('cong_ty.view_nhan_vien_cua_cong_ty',['ma' => $cong_ty->ma]) }}">
					Xem nhân viên của công ty
				</a>
			</td>
			@if (Session::get('cap_do')==1)
				<td>
					<a href="{{ route('cong_ty.view_update',['ma' => $cong_ty->ma]) }}">
						Sửa
					</a>
				</td>
				<td>
					<a href="{{ route('cong_ty.delete',['ma' => $cong_ty->ma]) }}">
						Xoá
					</a>
				</td>
			@endif
		</tr>
	@endforeach
</table>
{{$array_cong_ty->appends(['tim_kiem' => $tim_kiem])->links()}}
@endsection

resources/views/cong_ty/view_insert.blade.php
<form action="{{ route('cong_ty.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	Email
	<input type="email" name="email">
	<br>
	SDT
	<input type="text" name="sdt">
	<br>
	Địa chỉ
	<textarea name="dia_chi"></textarea>
	<br>
	<button>Thêm</button>
</form>

resources/views/cong_ty/view_update.blade.php
<form action="{{ route('cong_ty.update',['ma' => $cong_ty->ma]) }}" method="post">
	<input type='hidden' value='PUT' name='_method'>
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $cong_ty->ten }}">
	<br>
	Email
	<input type="email" name="email" value="{{ $cong_ty->email }}">
	<br>
	SDT
	<input type="text" name="sdt" value="{{ $cong_ty->sdt }}">
	<br>
	Địa chỉ
	<textarea name="dia_chi">{{ $cong_ty->dia_chi }}</textarea>
	<br>
	<button>Sửa</button>
</form>