routes/web.php
<?php

Route::get('show','Controller@show');
Route::get('test','Controller@test');
Route::post('upload','Controller@upload')->name('upload');

Route::get("view_login","LoginController@view_login")->name('view_login');
Route::post("process_login","LoginController@process_login")->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get("welcome","Controller@welcome")->name('welcome');
	Route::get("logout","LoginController@logout")->name('logout');

	$controller = "CongTyController";
	Route::group(["prefix" => "cong_ty", 'as' => 'cong_ty.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::group(['middleware' => 'CheckSuperAdmin'],function() use ($controller){
			Route::get("view_insert","$controller@view_insert")->name("view_insert");
			Route::post("process_insert","$controller@process_insert")->name("process_insert");
			Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
			Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
			Route::get("delete/{ma}","$controller@delete")->name("delete");

			// xem nhân viên của công ty
			Route::get("view_nhan_vien_cua_cong_ty/{ma}","$controller@view_nhan_vien_cua_cong_ty")->name("view_nhan_vien_cua_cong_ty");
		});
	});

	$controller = "NhanVienController";
	Route::group(["prefix" => "nhan_vien", 'as' => 'nhan_vien.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");

		Route::get("view_import_excel","$controller@view_import_excel")->name("view_import_excel");
		Route::post("process_import_excel","$controller@process_import_excel")->name("process_import_excel");
	});

	Route::resource('cong_ty_demo','CongTyDemoController');
});

app/Models/NhanVien.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class NhanVien extends Model
{
    use Notifiable;
    protected $table = 'nhan_vien';
    protected $fillable = [
    	'ten',
    	'ngay_sinh',
    	'email',
        'gioi_tinh',
    	'ma_cong_ty'
    ];
    protected $primaryKey = 'ma';

    public $timestamps = false;
    public function cong_ty()
    {
    	return $this->belongsTo('App\Models\CongTy','ma_cong_ty');
    }
}

app/Http/Controllers/NhanVienController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\Models\NhanVien;
use App\Models\CongTy;
use App\Http\Requests\NhanVienRequest;
use App\Notifications\NewStudent;
use App\Imports\NhanVienImport;
use Maatwebsite\Excel\Facades\Excel;

class NhanVienController
{
    public function view_all()
    {
        $array_nhan_vien = NhanVien::with('cong_ty')->get();


        return view('nhan_vien.view_all',[
        	'array_nhan_vien' => $array_nhan_vien,
        ]);
    }
    public function view_insert()
    {
        $array_cong_ty = CongTy::all();
    	return view('nhan_vien.view_insert',['array_cong_ty' => $array_cong_ty]);
    }
    public function process_insert(Request $rq)
    {
    	$nhan_vien = NhanVien::create($rq->all());
        $nhan_vien->notify(new NewStudent($nhan_vien));

    	// return redirect()->route('nhan_vien.view_all')->with('sucess','Đã thêm thành công');
    }
    public function view_update($ma)
    {
    	$nhan_vien = NhanVien::find($ma);

    	return view('nhan_vien.view_update',['nhan_vien' => $nhan_vien]);
    }
    public function process_update($ma,Request $rq)
    {
    	NhanVien::find($ma)->update($rq->all());

    	return redirect()->route('nhan_vien.view_all')->with('sucess','Đã sửa thành công');
    }
    public function delete($ma)
    {
    	NhanVien::find($ma)->delete();

    	return redirect()->route('nhan_vien.view_all')->with('sucess','Đã xoá thành công');
    }
    public function view_import_excel()
    {
        return view('nhan_vien.view_import_excel');
    }
    public function process_import_excel(Request $rq)
    {
        Excel::import(new NhanVienImport, $rq->file_excel);
    }
}

resources/views/nhan_vien/view_all.blade.php
<a href="{{ route('nhan_vien.view_insert') }}">
	Thêm
</a>
<br>
<a href="{{ route('nhan_vien.view_import_excel') }}">
	Thêm bằng Excel
</a>
@if (Session::has('sucess'))
	<h1>
		{{ Session::get('sucess') }}
	</h1>
@endif
<table border="1" width="100%">
	<tr>
		<th>
			Tên
		</th>
		<th>
			Giới tính
		</th>
		<th>
			Ngày sinh
		</th>
		<th>
			Tên Công Ty
		</th>
		<th>
			Sửa
		</th>
		<th>
			Xoá
		</th>
	</tr>
	@foreach ($array_nhan_vien as $nhan_vien)
		<tr>
			<td>
				{{ $nhan_vien->ten }}
			</td>
			<td>
				{{ $nhan_vien->gioi_tinh }}
			</td>
			<td>
				{{ $nhan_vien->ngay_sinh }}
			</td>
			<td>
				{{ $nhan_vien->cong_ty->ten }}
			</td>
			<td>
				<a href="{{ route('nhan_vien.view_update',['ma' => $nhan_vien->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('nhan_vien.delete',['ma' => $nhan_vien->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

resources/views/nhan_vien/view_import_excel.blade.php
<form action='{{ route('nhan_vien.process_import_excel') }}' method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	Chọn file Excel
	<input type="file" name="file_excel">
	<button>OK</button>
</form>

resources/views/nhan_vien/view_insert.blade.php
<form action="{{ route('nhan_vien.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ old('ten') }}">
	{{ $errors->first('ten') }}
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh" value="{{ old('ngay_sinh') }}">
	{{ $errors->first('ngay_sinh') }}
	<br>
	Email
	<input type="text" name="email" value="{{ old('email') }}">
	{{ $errors->first('email') }}
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1"
	@if (old('gioi_tinh')==1)
		checked 
	@endif>Nam
	<input type="radio" name="gioi_tinh" value="0"
	@if (old('gioi_tinh')==='0')
		checked 
	@endif>Nữ
	{{ $errors->first('gioi_tinh') }}
	<br>
	Công ty
	<select name="ma_cong_ty">
		@foreach ($array_cong_ty as $cong_ty)
			<option value="{{ $cong_ty->ma }}" 
			@if (old('ma_cong_ty')==$cong_ty->ma)
				selected 
			@endif>
				{{ $cong_ty->ten }}
			</option>
		@endforeach
	</select>
	{{ $errors->first('ma_cong_ty') }}
	<br>
	<button>Thêm</button>
</form>

resources/views/nhan_vien/view_update.blade.php
<form action="{{ route('nhan_vien.process_update',['ma' => $nhan_vien->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $nhan_vien->ten }}">
	<br>
	Email
	<input type="email" name="email" value="{{ $nhan_vien->email }}">
	<br>
	SDT
	<input type="text" name="sdt" value="{{ $nhan_vien->sdt }}">
	<br>
	Địa chỉ
	<textarea name="dia_chi">{{ $nhan_vien->dia_chi }}</textarea>
	<br>
	<button>Sửa</button>
</form>