routes/web.php
<?php

Route::get('show','Controller@show');
Route::get('test','Controller@test');
Route::post('upload','Controller@upload')->name('upload');

Route::get("view_login","LoginController@view_login")->name('view_login');
Route::post("process_login","LoginController@process_login")->name('process_login');

Route::group(['middleware' => 'CheckGiaoVu'],function(){
	Route::get("welcome","Controller@welcome")->name('welcome');
	Route::get("logout","LoginController@logout")->name('logout');

	$controller = "CongTyController";
	Route::group(["prefix" => "cong_ty", 'as' => 'cong_ty.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::group(['middleware' => 'CheckSuperAdmin'],function() use ($controller){
			Route::get("view_insert","$controller@view_insert")->name("view_insert");
			Route::post("process_insert","$controller@process_insert")->name("process_insert");
			Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
			Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
			Route::get("delete/{ma}","$controller@delete")->name("delete");

			// xem nhân viên của công ty
			Route::get("view_nhan_vien_cua_cong_ty/{ma}","$controller@view_nhan_vien_cua_cong_ty")->name("view_nhan_vien_cua_cong_ty");
		});
	});

	$controller = "NhanVienController";
	Route::group(["prefix" => "nhan_vien", 'as' => 'nhan_vien.'],function() use ($controller){
		Route::get("","$controller@view_all")->name("view_all");
		Route::get("view_insert","$controller@view_insert")->name("view_insert");
		Route::post("process_insert","$controller@process_insert")->name("process_insert");
		Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
		Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
		Route::get("delete/{ma}","$controller@delete")->name("delete");

		Route::get("view_import_excel","$controller@view_import_excel")->name("view_import_excel");
		Route::post("process_import_excel","$controller@process_import_excel")->name("process_import_excel");
	});

	Route::resource('cong_ty_demo','CongTyDemoController');
});

app/Http/Controllers/CongTyDemoController.php
<?php

namespace App\Http\Controllers;

use App\Models\CongTy;
use Illuminate\Http\Request;

class CongTyDemoController extends Controller
{
    protected $folder = 'cong_ty_demo';
    public function index()
    {
        $array_cong_ty = CongTy::all();

        return view("$this->folder.index",['array_cong_ty' => $array_cong_ty]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CongTy  $congTy
     * @return \Illuminate\Http\Response
     */
    public function show(CongTy $congTy)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CongTy  $congTy
     * @return \Illuminate\Http\Response
     */
    public function edit(CongTy $cong_ty)
    {
        return view('cong_ty.view_update',['cong_ty' => $cong_ty]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CongTy  $congTy
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CongTy $cong_ty)
    {
        $cong_ty->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CongTy  $congTy
     * @return \Illuminate\Http\Response
     */
    public function destroy(CongTy $cong_ty)
    {
        $cong_ty->delete();
    }
}

resources/views/cong_ty_demo/index.blade.php
<a href="{{ route('cong_ty.create') }}">
	Thêm
</a>
@if (Session::has('sucess'))
	<h1>
		{{ Session::get('sucess') }}
	</h1>
@endif
<table border="1" width="100%">
	<tr>
		<th>
			Tên
		</th>
		<th>
			SDT
		</th>
		<th>
			Email
		</th>
		<th>
			Địa chỉ
		</th>
		<th>
			Xem
		</th>
		<th>
			Sửa
		</th>
		<th>
			Xoá
		</th>
	</tr>
	@foreach ($array_cong_ty as $cong_ty)
		<tr>
			<td>
				{{ $cong_ty->ten }}
			</td>
			<td>
				{{ $cong_ty->sdt }}
			</td>
			<td>
				{{ $cong_ty->email }}
			</td>
			<td>
				{{ $cong_ty->dia_chi }}
			</td>
			<td>
				<a href="{{ route('cong_ty.show',['ma' => $cong_ty->ma]) }}">
					Xem nhân viên của công ty
				</a>
			</td>
			<td>
				<a href="{{ route('cong_ty.edit',['ma' => $cong_ty->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('cong_ty.destroy',['ma' => $cong_ty->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

resources/views/cong_ty_demo/view_insert.blade.php
<form action="{{ route('cong_ty.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	Email
	<input type="email" name="email">
	<br>
	SDT
	<input type="text" name="sdt">
	<br>
	Địa chỉ
	<textarea name="dia_chi"></textarea>
	<br>
	<button>Thêm</button>
</form>

resources/views/cong_ty_demo/view_update.blade.php
<form action="{{ route('cong_ty.process_update',['ma' => $cong_ty->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $cong_ty->ten }}">
	<br>
	Email
	<input type="email" name="email" value="{{ $cong_ty->email }}">
	<br>
	SDT
	<input type="text" name="sdt" value="{{ $cong_ty->sdt }}">
	<br>
	Địa chỉ
	<textarea name="dia_chi">{{ $cong_ty->dia_chi }}</textarea>
	<br>
	<button>Sửa</button>
</form>